# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-28 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betting',
            old_name='Odds',
            new_name='odds',
        ),
        migrations.RenameField(
            model_name='debate',
            old_name='Odds',
            new_name='odds1',
        ),
        migrations.RenameField(
            model_name='debate',
            old_name='odd1',
            new_name='odds2',
        ),
        migrations.AddField(
            model_name='betting',
            name='player',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
